### ISSUE TITLE
Exporting FBX Causes Unintended Results

### ISSUE THREAD

**Issue by jasonmerc** [AutumnFloof/HL-Modding-Guide#2]
I've followed the guide exactly, but when I get to the part where I import the FBX into UE4, my imported objects are not the same as yours.  From the GIF in your guide, your imported object appears to have a purple band.  Mine has a bright pink band, and an accompanying yellow PhysicsAsset object attached to it as well.

I think this is causing my wand replacement to not work, since something is different between our projects.  Deleting this extraneous object does not make it work.  I've done everything to try and make it work (add "_P", remove the textures, etc.) but my mod is still broken.

Can the author please revise this part of the guide: specifically exporting from Blender 2.83 to then import into UE4?  This part specifically seems to be causing some issues.

**Comment by AutumnFloof** [comment]
Helped on discord
