### ISSUE TITLE
Importing our own custom model

### ISSUE THREAD

**Issue by CucoMonster** [AutumnFloof/HL-Modding-Guide#3]
Hello. I wasn't sure if there was a way to DM you for this so my apologies if I am asking in the wrong section. I love your tutorial and I am reading it over and I am just wondering on this part:

> **"The next step is to import your own custom model. This can be whatever your imagination can think of ;)"**

I am new to blender and everything on this tutorial to be honest so I am wondering what file type this new model needs to be? And to import it do I follow the same steps as importing the in game wand [file > import > skeleton mesh (.psk)]? or is there a different way I need to import this? Your tutorial is very detailed which I love but this part wasn't as detailed which confused me a bit.

Also do you have any recommendations as to where I can find models I can use in this tutorial? I just want to give it a try but I honestly don't have any model or would know where to find such things (searching on google "free .psk model mesh" gave me no real results lol)

Thank you in advance.

**Comment by AutumnFloof** [comment]
Hey there, you can join the Nexus Modding discord, link is towards the bottom they have tons of people who can help. Generally you can just search for the object you want in Google and add "3d model" at the end. Almost any file format like obj or fbx that blender supports can be used. I can be found in that discord if you'd like to contact me directly! Happy Modding!

**Comment by CucoMonster** [comment]
Great. Thank you!
